In [1]:
import tensorflow as tf

create tensor 

In [2]:
scalar = tf.constant(7)
print(scalar.ndim)
scalar

0


<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
vector = tf.constant([10,12])
print(vector.ndim)
vector

1


<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 12])>

In [4]:
matrix = tf.constant([[10,7],[7,10]])
print(matrix.ndim)
matrix

2


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]])>

In [5]:
tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                       [[3,2,3],
                       [4,7,6]],
                       [[1,2,3],
                       [1,0,6]]])
print(tensor.ndim)
tensor

3


<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6]],

       [[3, 2, 3],
        [4, 7, 6]],

       [[1, 2, 3],
        [1, 0, 6]]])>

tensor variable : `tf.variable`

In [6]:
changeble = tf.Variable([10,7])
changeble[0].assign(11)
changeble

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([11,  7])>

In [7]:
random1 = tf.random.Generator.from_seed(1)
random1 = random1.normal(shape=(3,2))
random2 = tf.random.Generator.from_seed(1)
random2 = random2.normal(shape=(3,2))

random1 == random2, random1, random2 

(<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.43842274, -0.53439844],
        [-0.07710262,  1.5658046 ],
        [-0.1012345 , -0.2744976 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.43842274, -0.53439844],
        [-0.07710262,  1.5658046 ],
        [-0.1012345 , -0.2744976 ]], dtype=float32)>)

[tf.random.set_seed()](https://www.tensorflow.org/api_docs/python/tf/random/set_seed)

In [8]:
a = tf.constant([[10,7],[4,11],[5,13]])
b = tf.random.set_seed(1)
b = tf.random.shuffle(a)
b

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 5, 13],
       [ 4, 11]])>

Numpy arrays to Tensorflow tensor

In [9]:
import numpy as np

In [10]:
A = np.arange(1,31)
A


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [11]:
T = tf.constant(A,shape=(3,5,2))
T

<tf.Tensor: shape=(3, 5, 2), dtype=int32, numpy=
array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]],

       [[11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20]],

       [[21, 22],
        [23, 24],
        [25, 26],
        [27, 28],
        [29, 30]]])>

In [12]:
t = tf.random.set_seed(1)
t = tf.random.uniform((3,1,3,4),11,22,dtype=tf.int32)
print(t.ndim)
t

4


<tf.Tensor: shape=(3, 1, 3, 4), dtype=int32, numpy=
array([[[[13, 16, 11, 13],
         [16, 20, 18, 19],
         [12, 16, 11, 17]]],


       [[[19, 17, 21, 19],
         [15, 16, 12, 17],
         [18, 21, 20, 18]]],


       [[[19, 13, 20, 13],
         [12, 15, 17, 20],
         [21, 20, 12, 17]]]])>

In [13]:
t[:,:,:2,2:]

<tf.Tensor: shape=(3, 1, 2, 2), dtype=int32, numpy=
array([[[[11, 13],
         [18, 19]]],


       [[[21, 19],
         [12, 17]]],


       [[[20, 13],
         [17, 20]]]])>

In [14]:
var = tf.random.uniform((2,1,3,2),1,9,dtype=tf.int32)
var = tf.Variable(var)
var

<tf.Variable 'Variable:0' shape=(2, 1, 3, 2) dtype=int32, numpy=
array([[[[1, 7],
         [1, 6],
         [5, 6]]],


       [[[4, 2],
         [3, 1],
         [4, 4]]]])>

In [15]:
var[1,:,:,1].assign([[0,0,1]])
var

<tf.Variable 'Variable:0' shape=(2, 1, 3, 2) dtype=int32, numpy=
array([[[[1, 7],
         [1, 6],
         [5, 6]]],


       [[[4, 0],
         [3, 0],
         [4, 1]]]])>

add dimention > tf.newaxis = tf.expand_dim

In [16]:
a = tf.constant([[1,2],[3,4],[5,6]])
a

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]])>

In [17]:
print(a[:,:,tf.newaxis])
print(a[:,tf.newaxis,:])

tf.Tensor(
[[[1]
  [2]]

 [[3]
  [4]]

 [[5]
  [6]]], shape=(3, 2, 1), dtype=int32)
tf.Tensor(
[[[1 2]]

 [[3 4]]

 [[5 6]]], shape=(3, 1, 2), dtype=int32)


In [18]:
# axis = shape index (0,1,2,3,...) # add dimention 
print(tf.expand_dims(a,axis=2)) # add to column
print(tf.expand_dims(a,axis=1)) # add to row
print(tf.expand_dims(a,axis=0)) #add to channel (layer)

tf.Tensor(
[[[1]
  [2]]

 [[3]
  [4]]

 [[5]
  [6]]], shape=(3, 2, 1), dtype=int32)
tf.Tensor(
[[[1 2]]

 [[3 4]]

 [[5 6]]], shape=(3, 1, 2), dtype=int32)
tf.Tensor(
[[[1 2]
  [3 4]
  [5 6]]], shape=(1, 3, 2), dtype=int32)


tensor operation

In [19]:
tensor = tf.constant([[1,2],[3,4]])
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [20]:
a = tf.math.add(tensor, 10)
s = tf.math.subtract(tensor, 1)
m = tf.math.multiply(tensor, 2)
d = tf.math.divide(tensor, 2)
a, s, m, d, tensor


(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[11, 12],
        [13, 14]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[0, 1],
        [2, 3]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[2, 4],
        [6, 8]])>,
 <tf.Tensor: shape=(2, 2), dtype=float64, numpy=
 array([[0.5, 1. ],
        [1.5, 2. ]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4]])>)

Matrix multiplication

In [21]:
t = tf.constant([[2,3],[3,5],[0,1]])
w = tf.constant([[1,3],[10,2],[4,7]])
t , w

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[2, 3],
        [3, 5],
        [0, 1]])>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 1,  3],
        [10,  2],
        [ 4,  7]])>)

In [22]:
tf.transpose(w)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 1, 10,  4],
       [ 3,  2,  7]])>

In [23]:
tf.linalg.matmul(t,tf.transpose(w)) # same as t @ w  , transpoese shape for multiplication

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[11, 26, 29],
       [18, 40, 47],
       [ 3,  2,  7]])>

change dtype to improve speed

In [24]:
a = tf.constant([[1,2],[3,4]])
a.dtype

tf.int32

In [25]:
a = tf.cast(a, dtype=tf.float16)
a

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float16)>

tensor agg

In [26]:
t = tf.constant(np.random.randint(10,30,size=30),dtype=tf.float32)
print(t)
print('max :',tf.reduce_max(t))
print('idx max :',tf.argmax(t)) # index of maximum value
print(t[tf.argmax(t)])
print()
print('mean :',tf.reduce_mean(t))
print('sum :', tf.reduce_sum(t))
print('SD :',tf.math.reduce_std(t))
print('varintce :',tf.math.reduce_variance(t)) 
print('varintce is SD**2 :',tf.math.reduce_variance(t)**(1/2))

tf.Tensor(
[16. 18. 11. 15. 17. 24. 16. 11. 17. 16. 17. 22. 27. 14. 16. 12. 11. 14.
 18. 13. 14. 12. 29. 13. 14. 12. 19. 27. 29. 15.], shape=(30,), dtype=float32)
max : tf.Tensor(29.0, shape=(), dtype=float32)
idx max : tf.Tensor(22, shape=(), dtype=int64)
tf.Tensor(29.0, shape=(), dtype=float32)

mean : tf.Tensor(16.966667, shape=(), dtype=float32)
sum : tf.Tensor(509.0, shape=(), dtype=float32)
SD : tf.Tensor(5.2629733, shape=(), dtype=float32)
varintce : tf.Tensor(27.698889, shape=(), dtype=float32)
varintce is SD**2 : tf.Tensor(5.2629733, shape=(), dtype=float32)


remove 1 dimention of tensor

In [27]:
t = tf.constant(tf.random.uniform([30]), shape=(1,1,1,2,15))
print(t.shape,t,'\n')
ts = tf.squeeze(t)
ts.shape, ts

(1, 1, 1, 2, 15) tf.Tensor(
[[[[[0.8292774  0.634228   0.5147276  0.39108086 0.5809028  0.04848182
     0.1776321  0.70470166 0.49190843 0.3460425  0.5079107  0.2216742
     0.8485558  0.94408786 0.52639234]
    [0.3821411  0.2798195  0.0337733  0.43190658 0.09417534 0.96515214
     0.75696373 0.6727526  0.5339211  0.32353437 0.39806926 0.19708812
     0.8257885  0.15289044 0.60246646]]]]], shape=(1, 1, 1, 2, 15), dtype=float32) 



(TensorShape([2, 15]),
 <tf.Tensor: shape=(2, 15), dtype=float32, numpy=
 array([[0.8292774 , 0.634228  , 0.5147276 , 0.39108086, 0.5809028 ,
         0.04848182, 0.1776321 , 0.70470166, 0.49190843, 0.3460425 ,
         0.5079107 , 0.2216742 , 0.8485558 , 0.94408786, 0.52639234],
        [0.3821411 , 0.2798195 , 0.0337733 , 0.43190658, 0.09417534,
         0.96515214, 0.75696373, 0.6727526 , 0.5339211 , 0.32353437,
         0.39806926, 0.19708812, 0.8257885 , 0.15289044, 0.60246646]],
       dtype=float32)>)

One-hot encoding

In [44]:
foo = [0,3,2,4]
foo = tf.one_hot(foo, depth=5, on_value=1., off_value=0.2)
foo

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[1. , 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 1. , 0.2],
       [0.2, 0.2, 1. , 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 1. ]], dtype=float32)>

Square, log, .. some math

In [59]:
a = tf.range(1,6,dtype=tf.float32)
print(a)
print(tf.square(a))
print(tf.sqrt(a))
print(tf.math.log(a))

tf.Tensor([1. 2. 3. 4. 5.], shape=(5,), dtype=float32)
tf.Tensor([ 1.  4.  9. 16. 25.], shape=(5,), dtype=float32)
tf.Tensor([0.99999994 1.4142134  1.7320508  1.9999999  2.236068  ], shape=(5,), dtype=float32)
tf.Tensor([0.        0.6931472 1.0986123 1.3862944 1.609438 ], shape=(5,), dtype=float32)
